"""add thema

Revision ID: 014873d8d134
Revises: 8e5be10bd17c
Create Date: 2024-11-06 18:53:36.676170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014873d8d134'
down_revision: Union[str, None] = '8e5be10bd17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['theme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_theme_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theme_id'))

    op.drop_table('theme')
    # ### end Alembic commands ###
