"""add references field to verse

Revision ID: 626c29e6f97f
Revises: 0f76756e7424
Create Date: 2024-10-24 17:03:21.724081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626c29e6f97f'
down_revision: Union[str, None] = '0f76756e7424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refs', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verse', schema=None) as batch_op:
        batch_op.drop_column('refs')

    # ### end Alembic commands ###
