"""add code field to chapter and verse

Revision ID: 8db0bbec1d36
Revises: e18d656d73d5
Create Date: 2024-10-17 20:10:14.515041

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8db0bbec1d36"
down_revision: Union[str, None] = "e18d656d73d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chapter", schema=None) as batch_op:
        batch_op.add_column(sa.Column("code", sa.String(), nullable=False))

    with op.batch_alter_table("verse", schema=None) as batch_op:
        batch_op.add_column(sa.Column("code", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("verse", schema=None) as batch_op:
        batch_op.drop_column("code")

    with op.batch_alter_table("chapter", schema=None) as batch_op:
        batch_op.drop_column("code")

    # ### end Alembic commands ###
