"""add comment field to bible

Revision ID: 8e5be10bd17c
Revises: 626c29e6f97f
Create Date: 2024-10-25 11:20:38.884994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5be10bd17c'
down_revision: Union[str, None] = '626c29e6f97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bible', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bible', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
