"""schema create

Revision ID: e18d656d73d5
Revises: 
Create Date: 2024-10-11 19:25:56.966807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18d656d73d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_language_id'), ['id'], unique=False)

    op.create_table('bible',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('src', sa.String(length=1024), nullable=True),
    sa.Column('src_url', sa.String(length=1024), nullable=True),
    sa.Column('lang_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lang_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bible', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bible_id'), ['id'], unique=False)

    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=256), nullable=True),
    sa.Column('category', sa.Enum('OLD', 'NEW', 'APOCRYPHAL', name='booktypeenum'), nullable=True),
    sa.Column('bible_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bible_id'], ['bible.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_id'), ['id'], unique=False)

    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_id'), ['id'], unique=False)

    op.create_table('verse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtitle', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.String(length=4096), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verse_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verse_id'))

    op.drop_table('verse')
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_id'))

    op.drop_table('chapter')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_id'))

    op.drop_table('book')
    with op.batch_alter_table('bible', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bible_id'))

    op.drop_table('bible')
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_language_id'))

    op.drop_table('language')
    # ### end Alembic commands ###
