"""Book model : update category field definition

Revision ID: be85660b31e8
Revises: deb03ada95f9
Create Date: 2024-09-25 22:22:25.313003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be85660b31e8'
down_revision: Union[str, None] = 'deb03ada95f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('OLD', 'NEW', name='booktypeenum'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
