name: Build file

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/app

    steps:
    - uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '^3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: make install

    - name: Updates python path
      run: |
        echo "PYTHONPATH=$PYTHONPATH:." >> $GITHUB_ENV

    - name: Init test db
      run : make pretest

    - name: Run tests
      run: make testcov

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
          token: ${{ secrets.CODECOV_TOKEN }}

    - name: Clean up
      run: make clean